### ISSUE TITLE
Update react to ^15.0.0 in peerDependencies

### ISSUE THREAD

**Issue by samclement** [QubitProducts/qubit-react#16]
Peer dependencies need to be in-line with the applications that consume this library. This is not ideal and strengthens the case for a Qubit API that exposes segments independent of presentation stack.

**Comment by samclement** [comment]
Peer dependencies need to be in-line with the applications that consume this library. This is not ideal and strengthens the case for a Qubit API that exposes segments independent of presentation stack.

**Comment by oliverwoodings** [comment]
Hi @samclement , thanks for the issue. We're going to just remove the peerDependency all together, since it doesn't really achieve much (the possibility of a future version of React breaking this lib is minimal since we touch a very limited surface area of the React API).

Regarding an API for exposing underlying Qubit data such as segments; this library was never intended to serve that purpose - it is designed to provide interop between React-based interfaces and Qubit's main method of delivering experiences (JavaScript written in the Qubit experience editor). We are very keen to start exposing the underlying data and have various projects on our roadmap/backlog to address this - I believe @jhollingworth recently spoke to you guys about this.
