### ISSUE TITLE
Feature Request: Disable Experiences via Prop

### ISSUE THREAD

**Issue by trippingtarballs** [QubitProducts/qubit-react#25]
Would be cool to be able to enable/disable Experiences support by setting the prop of the `<QubitReact/>` component ... in this way, using fetched config, Experiences could be enabled/disabled via feature flags.

**Comment by KwanMan** [comment]
Hey @rbose85 , unfortunately it is not that simple. Even though the prop can disable the rendering of the variation, on our platform we would still track it as the user seeing a variation. This is because the wrapper has no concept of an Experiences, it is merely a mechanism to allow an external service to modify the DOM within your React tree.

This is something we could explore though as I can see this potentially being very useful to developers. Can you give me a specific use case where you want this functionality?

(cc @oliverwoodings )

**Comment by oliverwoodings** [comment]
I could imagine us providing this functionality through a different API than the wrapper itself (since, as @KwanMan says, the `<QubitReact />` component has no way to control the decision making process behind when experiences fire, only how they fire). Potentially we could provide a hook into the activation process through our `window.onQubitReady` API?

**Comment by jarjarbose** [comment]
@KwanMan @oliverwoodings thanks for the input. Sorry for my slow reply (I had forgotten I'd opened the Issue 😊) ...

Honestly, my thinking is more from a _dev_ / _QA_ point of view more than anything else. As a developer of a webapp that's using `<QubitReact />`, I want to be able to see what my page looks like with and without an Experiences enabled. Imagine a scenario where `<QubitReact />` is causing sufficient augmentation of my webapp that it has an impact on my regression tests. Obviously, in dev-mode, tracked variation should be omitted from any results-set. However, I see how all this would make for more work on the backend of Qubit.

**Comment by oliverwoodings** [comment]
@lambdabose that use case is definitely a valid one and is something we have been considering recently (might be some documentation appearing on our docs site soon). I think that in general the disabling/enabling of experiences for QA testing purposes is a problem that needs to be solved at a higher level than this library - at the end of the day, the react wrapper is just a mechanism for _executing_ an experience, whereas what you want to control in this situation is the _activation_.

**Comment by oliverwoodings** [comment]
cc @KidkArolis

**Comment by trippingtarballs** [comment]
Closing this issue. I believe our ideas have been successfully exchanged.
